language: go
go:
- tip
install: true
script:
- go test -v .
- mkdir bin
before_deploy:
- GOARCH=arm GOOS=linux go build -o bin/replication-manager-$GOOS-$GOARCH
- GOARCH=386 GOOS=linux go build -o bin/replication-manager-$GOOS-$GOARCH
- GOARCH=amd64 GOOS=linux go build -o bin/replication-manager-$GOOS-$GOARCH
deploy:
  provider: releases
  api_key:
    secure: ChyLl/faqOEJyrAULXGBQW6yQg8tg9x5qI9cgXgasujT1Zv/WwDiBXB/5Z3NcVK5MU8xyKVhS7Y03jh+Wt/npgytYBNJKGXijHPXuKpfF35tBdyJgqGEH7jaoOxdnZWukkh6GpKSrY23bGTQeaaRuOuRE1++l8C10pHHXoUQ4hbKuQv0V03G6f811JzCnoG+ARKT0/Nc0lUc15cxlUiK/Oo8xbRPmQC0u5H+c4WSN2MXRyKTYzL57roikqjTk4TvJBF5UosVGCkWZZGc9OZtGUH06+SmkfK52tfn11NDoapCtQ4Js0ftdWNYm7AMb6eoxrj/j7SfXfk/AXTm/qiNN4amWDE7+C8XHQOSIxpT4bF8u3GbOT/Q6xIhC/wPyW19mgNCMdI34wpqSRuCxP1u4ZpnD8BfEVcalj1+Vs3DfXQnA/B1UYAu6V6bkdF/1F0t63zSB1U9QZlWhYJAIAmImmBEiy2gSOhbnNJ33Pw/JW+/ilFM/cYjrzWSNnNlh3R7aDeMhLNo3w0ndX+xX0q0xM2Bwyf1X3QFwXE+YMyoxZ3Nf36L2XWtAw43WuRJpBadJTaPFIKT2IyoHTCA2ZXYAIjmu9LzuUiEkhKlAF8ILFascXPyLAB/BlIqk/V7exrqRgW83czVeIXk4ZmsmTyTbix6dZIMMpTdyPC4bZNxCo8=
  file: bin/replication-manager
  on:
    repo: signal18/replication-manager
    tags: true
  skip_cleanup: true
